### ISSUE TITLE
[BUG] Failure during WiFi setup in current ESPHome dev branch

### ISSUE THREAD

**Issue by mmakaay** [mmakaay/esphome-yeelight_bs2#103]
**Describe the bug**
A problem was reported where the current dev branch of ESPHome results in a lamp that is not starting.
It ends in a stacktrace dump.

I will investigate this on my dev lamp.

**Comment by mmakaay** [comment]
I wasn't able to reproduce the issue.

The original reporter got the lamp back to work by first disabling this part from the config:
```
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
#   sdkconfig_options:
#     CONFIG_FREERTOS_UNICORE: y
#   advanced:
#     ignore_efuse_mac_crc: true
```
then flashing via serial.
After this, he re-enabled the unicore and mac_crc stuff, flashed again over serial and the lamp started working again.

I have no explanation as for why this would work, but let's keep it in mind in case I get other reports.
