### ISSUE TITLE
[FEATURE] Support for Bluetooth Proxy

### ISSUE THREAD

**Issue by holefrog** [mmakaay/esphome-yeelight_bs2#107]
ESPHome supports Bluetooth Proxy now, by adding the follow:
```
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

I tried it in Yaml, but after flash, the lamp cannot turn on. So, I have to remove those lines.
