### ISSUE TITLE
[FEATURE]  Add support web OTA upgrade 

### ISSUE THREAD

**Issue by 0neday** [mmakaay/esphome-yeelight_bs2#109]
**Is your feature request related to a problem? Please describe.**

I found  esp-idf framework that is not support web ota upgrade
```
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
```

**Describe the solution you'd like**
do you have any plan to add web ota support using arduino framework?
like this 
```
esphome:
  name: yeelight-c900
  platformio_options:
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.6

  # avoid loop reboot when enable BLE
  on_loop:
    - lambda: "vTaskDelay(10/portTICK_PERIOD_MS);"

esp32:
  board: esp32dev
```
![1.PNG](https://s2.loli.net/2023/02/05/owvBGhbNPY7DSks.png)

https://github.com/0neday/yeelight-c900/blob/main/yeelight-c900.yaml#L5
