### ISSUE TITLE
Change ESP-IDF for another framework

### ISSUE THREAD

**Issue by PsychoRS** [mmakaay/esphome-yeelight_bs2#115]
Hi,

As webserver: component is not yet implemented (https://github.com/esphome/feature-requests/issues/1649) in ESPHome when using ESP-IDF framework, what framework should I use if I want that component in my firmware?

```
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
    # Bugfix for ESPHome 2022.12.0 and up: fallback to older platform
    # version, to prevent bricked devices. ESPHome uses newer versions
    # by default.
    # See also: https://github.com/mmakaay/esphome-xiaomi_bslamp2/issues/104
    version: 4.3.2
    source: ~3.40302.0
    platform_version: platformio/espressif32 @ 3.5.0
```
Thanks in advance
