### ISSUE TITLE
"Bricked" lamp after flashing wrong FW

### ISSUE THREAD

**Issue by ChickenFood** [mmakaay/esphome-yeelight_bs2#137]
Hi @mmakaay 
Thanks for the amazing work!

I have followed the guide up until flashing the lamp's esp32 but got confused and flashed a template configuration from HomeAssistant instead
Template FW didn't connect to wifi and didn't create a failsafe hotspot either
I tried to restore FW but it couldn't get any serial output from the lamp

Is there any way where I could factory reset the esp32 (via physical connection) so I can re-flash it with the example config you have provided?

i am using one of these to flash the FW (https://www.taiwaniot.com.tw/product/esp8266-esp-01s-wifi%E6%A8%A1%E7%B5%84%E4%B8%8B%E8%BC%89%E5%99%A8-esp-link-v1-0/)... These are viable right?

Also the following is the template config I have used

```
esphome:
  name: test
  friendly_name: TEST

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ****

ota:
  - platform: esphome
    password: ****

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: ***

captive_portal:
```

**Comment by randybb** [comment]
esp32 in this lamp is a singlecore with a mac written in eFuse, so a "special" config is needed. This is the reason why this is not working and just bootlooping. You can fix it by flashing it via UART - the steps are described here in the [flashing guide](https://github.com/mmakaay/esphome-xiaomi_bslamp2/blob/dev/doc/flashing.md).
That module is just usb to uart, so yes, it will work https://github.com/ldijkman/WT32-ETH01-LAN-8720-RJ45-/blob/main/USB%20to%20ESP-01%20Adapter%20schematic.pdf

And the special config is not so special, basically just the `esp32:` part needs to be changed:
```yaml
esp32:
  board: esp32doit-devkit-v1 # esp32dev would work too
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_custom_mac: true
      ignore_efuse_mac_crc: true
```
