### ISSUE TITLE
Binary output that exposes night light mode on/off

### ISSUE THREAD

**Issue by mmakaay** [mmakaay/esphome-yeelight_bs2#6]
It would be useful to know whether or not the night light mode is activated. While playing with the yaml configs, I found that I had to use this construction to detect night light mode (to turn off the front panel illumination when light mode was active):

```yaml
light:
  - platform: yeelight_bs2
    on_brightness:
      then:
        - output.set_level:
            level: !lambda if (x < 0.012f) return 0; else return x;
```

Having to use the magic number `0.012f` in there is not okay.

**Comment by mmakaay** [comment]
Well, why binary? I don't know really. The lamp has more modes available.
I added a text sensor, which propagates the active light mode as a string ("off", "rgb", "white" or "night").
Commit: https://github.com/mmakaay/esphome-yeelight_bs2/commit/d1d9ecea95eab8688500f9dd63f494d5558273a7

It's not enough to close this issue. I want an `on_state` automation for this text sensor, so we have a really easy way to act upon the various light modes ("when the lamp goes into night light mode, play the music box MP3 for 15 minutes", that kind off goodness ;-) )

**Comment by mmakaay** [comment]
I made it possible to use the text_sensor within logic expressions, so that fixes the magic number issue.
I can now use the following construct:

```yaml
light:
    on_brightness:
      then:
        - output.set_level:
            id: ${id_front_panel_output}
            level: !lambda |-
              if (id(${id_light_mode}).state == "night")
                return 0;
              else
                return x;
```
