### ISSUE TITLE
Warm white night light version

### ISSUE THREAD

**Issue by Staubgeborener** [mmakaay/esphome-yeelight_bs2#74]
This is not really a bug but a question about syntax and doing the correct coding.

I am using [this code snippet](https://github.com/mmakaay/esphome-xiaomi_bslamp2/issues/68#issuecomment-975652672) for my bedside lamp, which is working great. This code snippet can activate the night light by long pressing the power button:
```yaml
[...]
      then:
        - light.turn_on:
            id: my_light
            brightness: 1%
            red: 100%
            green: 0%
            blue: 0%
[...]
```

How can I use this to get a warm white version of the night light instead of a red one?
```yaml
      white:
        luke:        { color_temperature: 400 mireds      }
```
