### ISSUE TITLE
[BUG] Lamp becomes unavailable every hour

### ISSUE THREAD

**Issue by szymucha94** [mmakaay/esphome-yeelight_bs2#84]
**Describe the bug**
Lamp becomes unavailable at least once every hour when on. State "off" is maintained in HA even for days. Lamp is connected to wifi and it does not disconnect.

**To Reproduce**
Turn on the light
Enable the "fast random" mode
Leave it on for 1 hour
Check lamp entity history in HA

**Expected behavior**
Lamp should not be "unavailable" when on and with active wifi connection.

**Additional context**
versions used:
FW: Firmware: 2022.5.1 (Jun 14 2022, 22:21:11)
esphome addon: Current version: 2022.6.1

![21](https://user-images.githubusercontent.com/95378717/174502641-b71f9f11-444a-4b97-9e8d-3e43fcb73533.PNG)

**Comment by szymucha94** [comment]
Testing now with updated FW to the one based on 2022.6.1

**Comment by szymucha94** [comment]
Same problem on 2022.6.1.

**Comment by mmakaay** [comment]
I haven't seen this behavior on any of my three lamps, and with my development lamp,
I did some really long tests with exactly that effect without issues.
Maybe something changed in ESPHome core that now triggers this, so I will flash my dev lamp with the latest ESPHome code and see if I can reproduce this behavior.

One known thing that can trigger this, is excessive logging. The more you log, the less time the WiFi component has to keep up with network traffic. So one thing you could check, is what your logger configuration looks like. From the core config package:

```yaml
# The log level can be raised when needed for debugging the firmware. For
# production, a low log level is recommended. Mainly because high volume log
# output might interfere with the API/WiFi connection stability. So when
# raising the log level, beware that you might see dropped connections from
# Home Assistant and the network log viewer.
logger:
  level: WARN
```
