### ISSUE TITLE
[FEATURE] Add BTProxy

### ISSUE THREAD

**Issue by TheFes** [mmakaay/esphome-yeelight_bs2#96]
**Is your feature request related to a problem? Please describe.**
As HA now supports Bluetooth proxies, and the Xiaomi Bedside lamp 2 comes with an ESP, I thought it would be nice if it would also act as a Bluetooth proxy.
I tried adding it myself, which results in a successful OTA flash, but then the light doesn't work anymore. I had to flash a non-btproxy version using the ftdi-adapter again to make it work. So this could be some kind of hardware limitation, it could also be that I'm doing something wrong :)

This is what I added:
```yaml
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
```

**Describe the solution you'd like**
The lamp to act as a BT Proxy

**Describe alternatives you've considered**
Adding it myself, without success..
